services:
   flask-web-app:
      image: flask-app:1.0.0
      container_name: Flask-container
      networks:
         my-network:
            ipv4_address: 192.168.1.2 
      depends_on:
         - mysql-database

   mysql-database:
      image: mysql:latest
      networks:
         my-network:
            ipv4_address: 192.168.1.3
      volumes:
         - flask-volume:/flask-app/flask-volume:rw
      environment:
         - MYSQL_ROOT_PASSWORD=weak_password
         - MYSQL_PASSWORD=faible
         - MYSQL_USER=ben
         - MYSQL_DATABASE=users_database
   
networks:
   my-network:
      name: flask-network
      ipam:
         config:
            - subnet: 192.168.1.0/24
              gateway: 192.168.1.1

volumes:
   flask-volume:
     