services:
   flask-web-app:
      build: .
      container_name: Flask-container
      networks:
         my-network:
            ipv4_address: 192.168.1.2 
      depends_on:
         - mysql-database

   mysql-database:
      image: mysql:latest
      networks:
         my-network:
            ipv4_address: 192.168.1.3
      volumes:
         - flask-volume:/flask-app/flask-volume:rw
      environment:
         - MYSQL_ALLOW_EMPTY_PASSWORD="true"
   
networks:
   my-network:
      ipam:
         config:
            - subnet: 192.168.1.0/24
              gateway: 192.168.1.1

volumes:
   flask-volume:
            
         