services:
   flask-web-app:
      image: flask-app:1.0.0
      container_name: Flask-container
      networks:
         my-network:
            ipv4_address: 192.168.1.2 
      depends_on:
         - mysql-database

   mysql-database:
      image: mysql:latest
      networks:
         my-network:
            ipv4_address: 192.168.1.3
      volumes:
         - flask-volume:/flask-app/flask-volume:rw
      environment:
         - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
         - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
         - MYSQL_USER_FILE=/run/secrets/mysql_user
         - MYSQL_DATABASE_FILE=/run/secrets/mysql_database

      secrets:
         - mysql_root_password
         - mysql_password
         - mysql_user
         - mysql_database

networks:
   my-network:
      name: flask-network
      ipam:
         config:
            - subnet: 192.168.1.0/24
              gateway: 192.168.1.1

volumes:
   flask-volume:
     

secrets:
  
  mysql_root_password:
    file: ./mysql_root_password.txt
  mysql_password:
   file: ./mysql_password.txt 
  mysql_user:
   file: ./mysql_user.txt
  mysql_database:
   file: ./mysql_database.txt